mongo:
    image: mongo
    ports:
     - "127.0.0.1:27017:27017"
    volumes:
     - ../database:/data/db

memcached:
    image: memcached
    ports:
     - "127.0.0.1:11211:11211"

shiva1:
    extends:
        file: shiva.yml
        service: shiva
    links:
     - mongo:mongo
     - memcached:memcached
shiva2:
    extends:
        file: shiva.yml
        service: shiva
    links:
     - mongo:mongo
     - memcached:memcached
shiva3:
    extends:
        file: shiva.yml
        service: shiva
    links:
     - mongo:mongo
     - memcached:memcached

balancer:
    build: balancer
    links:
     - shiva1:shiva1
     - shiva2:shiva2
     - shiva3:shiva3
    ports:
     - "127.0.0.1:80:80"
