version: '2'

services:
    mongo1:
        image: mongo
        command: --replSet rs0 --enableMajorityReadConcern
        volumes:
         - ../database/mongo/1:/data/db
    mongo2:
        image: mongo
        command: --replSet rs0 --enableMajorityReadConcern
        volumes:
         - ../database/mongo/2:/data/db
    mongo3:
        image: mongo
        command: --replSet rs0 --enableMajorityReadConcern
        volumes:
         - ../database/mongo/3:/data/db

    hazelcast1:
        image: hazelcast/hazelcast
        environment:
         - JAVA_OPTS=-Dhazelcast.max.join.merge.target.seconds=3 -Dhazelcast.connect.all.wait.seconds=3 -Dhazelcast.merge.first.run.delay.seconds=3 -Dhazelcast.merge.next.run.delay.seconds=3 -Dhazelcast.operation.call.timeout.millis=3000 -Dhazelcast.max.no.heartbeat.seconds=9  -Dhazelcast.max.no.master.confirmation.seconds=15 -Dhazelcast.member.list.publish.interval.seconds=5 -Dhazelcast.master.confirmation.interval.seconds=7 -Dhazelcast.config=/data/hazelcast.xml
        volumes:
         - ./hazelcast:/data
    hazelcast2:
        image: hazelcast/hazelcast
        environment:
         - JAVA_OPTS=-Dhazelcast.max.join.merge.target.seconds=3 -Dhazelcast.connect.all.wait.seconds=3 -Dhazelcast.merge.first.run.delay.seconds=3 -Dhazelcast.merge.next.run.delay.seconds=3 -Dhazelcast.operation.call.timeout.millis=3000 -Dhazelcast.max.no.heartbeat.seconds=9  -Dhazelcast.max.no.master.confirmation.seconds=15 -Dhazelcast.member.list.publish.interval.seconds=5 -Dhazelcast.master.confirmation.interval.seconds=7 -Dhazelcast.config=/data/hazelcast.xml
        volumes:
         - ./hazelcast:/data
    hazelcast3:
        image: hazelcast/hazelcast
        environment:
         - JAVA_OPTS=-Dhazelcast.max.join.merge.target.seconds=3 -Dhazelcast.connect.all.wait.seconds=3 -Dhazelcast.merge.first.run.delay.seconds=3 -Dhazelcast.merge.next.run.delay.seconds=3 -Dhazelcast.operation.call.timeout.millis=3000 -Dhazelcast.max.no.heartbeat.seconds=9  -Dhazelcast.max.no.master.confirmation.seconds=15 -Dhazelcast.member.list.publish.interval.seconds=5 -Dhazelcast.master.confirmation.interval.seconds=7 -Dhazelcast.config=/data/hazelcast.xml
        volumes:
         - ./hazelcast:/data

    shiva1:
        extends:
            file: shiva.yml
            service: shiva
        depends_on:
         - mongo1
         - mongo2
         - mongo3
         - hazelcast1
         - hazelcast2
         - hazelcast3
    shiva2:
        extends:
            file: shiva.yml
            service: shiva
        depends_on:
         - mongo1
         - mongo2
         - mongo3
         - hazelcast1
         - hazelcast2
         - hazelcast3
    shiva3:
        extends:
            file: shiva.yml
            service: shiva
        depends_on:
         - mongo1
         - mongo2
         - mongo3
         - hazelcast1
         - hazelcast2
         - hazelcast3

    balancer:
        build:
            context: balancer
        ports:
         - "127.0.0.1:80:80"
        depends_on:
         - shiva1
         - shiva2
         - shiva3
