mongo:
    image: mongo
    ports:
     - "127.0.0.1:27017:27017"
    volumes:
     - ../database:/data/db
memcached:
    image: memcached
    ports:
     - "127.0.0.1:11211:11211"
shiva:
    build: shiva
    links:
     - mongo:mongo
     - memcached:memcached
    log_driver: "json-file"
    log_opt:
        max-size: "10m"
        max-file: "5"
    ports:
     - "127.0.0.1:8080:8080"
balancer:
    build: balancer
    links:
     - shiva:shiva
    ports:
     - "127.0.0.1:80:80"
